# Generated by Django 4.0.4 on 2022-05-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='pub_date',
            new_name='date',
        ),
    ]
